version: '3.8'
services:    
  game-backend:
    build: .
    container_name: "game-app"
    image: game:latest
    ports:
      - "8080:8080"
      - "9090:9090"
      - "8081:8081"
    networks:
      - backend-network    

networks:
  backend-network:
    driver: bridge